Remove python 2.7 tox checks
Latest ansible pip release 5.0.0 causes the error
ERROR: No matching distribution found for ansible-core<2.13,>=2.12.0
Since we use browbeat on OSP 13 rarely, python 2.7 tox checks can
be removed.

Change-Id: I4b6e3effd5c56eb8706daf423ff4360cd587e43d