Pin numpy<2.0.0
New numpy-2.0.0 release not compatible with used
elasticsearch version, since elasticsearch is
pinned also need to add upper cap for numpy to
avoid the issue.
With numpy-2.0.0 it fails like:-
AttributeError: `np.float_` was removed in the NumPy 2.0 release.
Use `np.float64` instead.

Change-Id: I8fd5a52ffad24ca3d90c6169574f08ddedb801e4